version: '3.1'
services:
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - 8080:80
    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        restart: unless-stopped
        expose:
            - 9000
